spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
