spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: hku7817343

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
